name: 'Gitbook Action Build'
on:
  push:
    branches:
      - master  # trigger branch
      - release/*
  workflow_dispatch:

#        pubdir=${branch//\/}
#        echo $branch
#        echo $pubdir

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout action
      uses: actions/checkout@v2
    - name: Get Branch
      run: |
        echo ${{ github.ref }}
        raw=$(git branch -r --contains ${{ github.ref }})
        echo $raw
        branch=${raw/origin\/}
        echo $branch
        echo "ON_PUSH_BRANCH_NAME=$branch" >> $GITHUB_ENV
        pubdir=${branch////-}
        echo /$pubdir
        echo "ON_PUSH_PUBDIR=/$pubdir" >> $GITHUB_ENV
    - name: Print Branch
      run: |
        echo ${{env.ON_PUSH_BRANCH_NAME}}
        echo "${{env.ON_PUSH_BRANCH_NAME}}"
        echo ${{env.ON_PUSH_PUBDIR}}
        echo "${{env.ON_PUSH_PUBDIR}}"
    - name: Gitbook Action
      uses: zanderzhao/gitbook-action@v1.2.2
      with:
        token: ${{secrets.PERSONAL_TOKEN}}
        source_branch: ${{env.ON_PUSH_BRANCH_NAME}}
        publish_branch: gh-pages
        publish_dir: ${{env.ON_PUSH_PUBDIR}}
        gitbook_pdf: true
        gitbook_epub: true
        gitbook_mobi: true
