name: 'Gitbook Action Build'
on:
  push:
    branches:
      - master  # trigger branch
      - release/*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout action
      uses: actions/checkout@v2
    - name: Get Branch
      uses: nelonoel/branch-name@v1
    - name: Gitbook Action
      uses: zanderzhao/gitbook-action@v1.2.2
      with:
        token: ${{ secrets.PERSONAL_TOKEN }}
        source_branch: ${BRANCH_NAME}
        publish_dir: ${BRANCH_NAME}
        gitbook_pdf: true
        gitbook_epub: true
        gitbook_mobi: true
