name: 'Gitbook Action Build'
on:
  push:
    branches:
      - master  # trigger branch
      - release/*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout action
      uses: actions/checkout@v2
    - name: Get Branch
      run: |
        raw=$(git branch -r --contains ${{ github.ref }})
        branch=${raw/origin\/}
        pubdir=${branch//\/}
        echo $branch
        echo $pubdir
        echo ::set-env name=BRANCH::$branch
        echo ::set-env name=PUBDIR::$pubdir
    - name: Gitbook Action
      uses: zanderzhao/gitbook-action@v1.2.2
      with:
        token: ${{ secrets.PERSONAL_TOKEN }}
        source_branch: ${{env.BRANCH}}
        publish_branch: gh-pages
        publish_dir: foo
        gitbook_pdf: true
        gitbook_epub: true
        gitbook_mobi: true
